### PR TITLE
Fix auth

### LINKED ISSUE #2: Can't login anymore
Many thanks for your continuing work on this project! Since last week I've run into an issue where I can't login anymore. I have tried all of the possible backends. Using the default `cloud` backend that I have alway used before, the request made at https://github.com/Smart123s/BeFake/blob/master/BeFake/BeFake.py#L217 receives the following response from the Identity Toolkit API:
```
{
  "error": {
    "code": 403,
    "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
    "errors": [
      {
        "message": "Requests from this Android client application \u003cempty\u003e are blocked.",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_ANDROID_APP_BLOCKED",
        "domain": "googleapis.com",
        "metadata": {
          "service": "identitytoolkit.googleapis.com",
          "consumer": "projects/405768487586"
        }
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by NicoWeio**
_If_ everything works (not only _login_ and _feed_, but also _memories_ etc.), this fixes #2 – [for now](https://github.com/userbradley/BeReal/discussions/49#discussioncomment-8138388).

Credits: https://github.com/rvaidun/befake/commit/6ae70ca3ecd8b90c1563c5d3939caa8326ce1f10

### CODE REVIEW

**Comment by NicoWeio** [comment]
Added a fix for token refreshing / 401 errors courtesy of https://github.com/Smart123s/BeFake/issues/4#issuecomment-1898346788.
Note that I didn't test that approach myself (yet).

**Comment by Smart123s** [comment]
Hi, sorry for taking so long to reply. Notifications were turned off on this repository for some reason, and I've only discovered this PR by accident.
First off, thanks a lot for opening this PR and taking the time to fix this script. To be honest, I don't really want to be a maintainer of this project, so I'll probably just start using your fork instead. As far as I've seen, you've already made some long overdue refactoring there.

The way you changed the headers doesn't only apply to the auth requests, but to all requests sent to BeReal. Given how much they are looking at this project, it could be safer to not use FirebaseAuth as the useragent to every request. Maybe separate the headers for the auth flow?
https://github.com/Smart123s/BeFake/pull/3/files#diff-530fe815c10fa2f7b52d0bd56be032acde2c30fd4f99067237011a2bb56ae6e7R81

**Comment by Smart123s** [comment]
I've separated the auth headers at https://github.com/Smart123s/BeFake/commit/30347f70c785dce5855caa677d19341a6e2da595 and https://github.com/Smart123s/BeFake/commit/923cf5b919b86231ce2ca3223f511529e72793c5. I'm lazy to open a PR, but feel free to cherry-pick those commits.

**Comment by NicoWeio** [comment]
Indeed, I have been working on some refactors, but – due to current time constraints – not in a particularly structured or comprehensive manner. I'm glad you could work around these in 366dcc11c8ffca83565308b6e9a660a6fa66c3ff, as it looks.
I'll gladly cherry-pick your changes in a minute. Thanks! :)

**Comment by NicoWeio** [comment]
Does 923cf5b919b86231ce2ca3223f511529e72793c5 actually work for you? I got it working after applying 4115e2c2d62030f634960b69077516e110188e02, but am not sure if this is what you intended.

**Comment by Smart123s** [comment]
You are right,I made a mistake and https://github.com/Smart123s/BeFake/commit/4115e2c2d62030f634960b69077516e110188e02 fixes it.

**Comment by Smart123s** [comment]
I actually have your commits in my repo now, so I'll close this PR.

**Pull request closed without merging**
